AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Metadata: {}
Parameters:
  OutputS3:
    Default: "testpipelineaarti"
    Description: Output S3 bucket 
    Type: String
  InputS3:
    Default: ""
    Description: Input S3 bucket 
    Type: String
  SecurityGroup:
    Default: "sg-000a9063e98308975"
    Description: Security Group for EC2 instance 
    Type: String
  PrimarySubnet:
    Default: "subnet-03c106fac9d1apcfe"
    Description: Subnet for EC2 instance
    Type: String
  RDSUsername:
    Default: ""
    Description: RDS Username
    Type: String
  RDSPassword:
    Default: ""
    Description: RDS Password
    Type: String
  RDSTable:
    Default: ""
    Description: RDS Table
    Type: String
  ShellCmd:
    Default: "echo Hello World!"
    Description: Shell command to clean dataset
    Type: String
  RDSConnection:
    Default: ""
    Description: RDS Connection String
    Type: String
  
Resources:
  DataPipelineDefaultResourceRole: 
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal: 
              Service: 
                - "s3:*"
                - "rds:*"
                - "ec2:Describe*"
                - "ec2:Start*"
                - "ec2:RunInstances"
                - "ec2:Stop*"
                - "datapipeline:*"
                - "cloudwatch:*"
            Action: 
              - "sts:AssumeRole"
  DataPipelineDefaultRole: 
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal: 
              Service: 
                - "datapipeline.amazonaws.com"
  S3Output:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref "OutputS3"
      VersioningConfiguration:
        Status: Enabled
